export type BotConfigTabId = "scan" | "enter" | "exit" | "risk";

export interface BotConfigSearchEntry {
  tab: BotConfigTabId;
  label: string;
  keywords: string[];
}

type AliasMap = Record<string, string[]>;

function entries(
  tab: BotConfigTabId,
  labels: string[],
  aliases: AliasMap = {},
): BotConfigSearchEntry[] {
  return labels.map((label) => ({
    tab,
    label,
    keywords: aliases[label] ?? [],
  }));
}

const scanLabels = [
  "Trading Style",
  "Instruments",
  "Spread Filter",
  "Max Spread (pips)",
  "ATR Filter",
  "ATR Min (pips)",
  "ATR Max (pips)",
  "Correlation Filter",
  "Sessions & Timing",
  "Asian Session",
  "London Session",
  "New York Session",
  "Off-Hours",
  "News Event Filter",
  "News Buffer (minutes)",
  "Scan Interval (minutes)",
  "Direction & Bias",
  "HTF Bias Timeframe",
  "HTF Bias Required",
  "HTF Bias Hard Veto",
  "Only Buy in Discount",
  "Only Sell in Premium",
  "Enable Regime Scoring",
  "Regime Strength",
  "Structural Conviction Gate",
  "Analysis Modules",
  "Order Blocks",
  "Fair Value Gaps",
  "Liquidity Pools",
  "Market Structure",
  "Displacement",
  "Breaker Blocks",
  "Unicorn Model",
  "Session Analysis",
  "SMT Divergence",
  "Volume Profile",
  "Trend Direction",
  "Daily Bias",
  "AMD Phase",
  "FOTSI",
  "Game Plan",
  "Enable Game Plan",
  "Direction Verdict Authority",
  "Gameplan Hierarchy Audit",
  "Bias Enforcement",
  "Game Plan Enforcement",
  "Minimum Plan Confidence",
  "Auto Key Levels",
  "Session Bias",
  "PD Levels",
  "IPDA Ranges",
  "Opening Range",
  "Enable Opening Range",
  "Candle Count",
  "OR Bias",
  "Judas Swing",
  "Key Levels",
  "Premium/Discount from OR",
  "Wait for OR Completion",
  "Precision Filters",
  "HTF Framework",
  "Displacement-Validated MSS",
  "Judas Swing / Liquidity Sweep",
  "FVG Invalidation Rules",
  "Kill Zones & Silver Bullet",
  "Risk Management",
  "Gate Mode",
  "Min Bias Strength",
  "Min Displacement Ratio",
  "Min Sweep (pips)",
  "Min Body Ratio",
  "KZ Buffer (min)",
  "SMC Enhancements",
  "Phase Detection",
  "Zone Lifecycle v2",
  "Fib 3-Point TP",
  "Trendline Liquidity",
  "Monthly Containment",
  "Consolidation Threshold",
  "Trend Threshold",
  "Max Retests",
  "Confidence Decay",
  "Min Displacement",
  "Size Multiplier",
  "Primary TP Level",
  "Min Touches",
  "Trap Touch #",
] as const;

const enterLabels = [
  "Scoring Engine",
  "Confluence Threshold (%)",
  "Min Zone Score",
  "Tier 1 Gate",
  "Min Tier 1 Factors",
  "Score Normalization",
  "Thesis Conviction",
  "Factor Weights",
  "Market Structure",
  "Order Block",
  "Fair Value Gap",
  "Premium/Discount & Fib",
  "PD/PW Levels",
  "Liquidity Sweep",
  "Displacement",
  "Reversal Candle",
  "Session Quality",
  "HTF POI Alignment",
  "HTF Fib + PD + Liquidity",
  "Confluence Stack",
  "Currency Strength",
  "SMT Divergence",
  "Daily Bias",
  "Breaker Block",
  "Unicorn Model",
  "Volume Profile",
  "AMD Phase",
  "Judas Swing",
  "Pullback Health",
  "GP Key Level",
  "Zone Engine",
  "Impulse Zone Gate Mode",
  "Max Fib Retracement",
  "Require Liquidity Sweep",
  "Quality Threshold (0-100)",
  "Max Age (bars)",
  "Min Body Ratio",
  "Min Displacement (ATR)",
  "Entry Timing",
  "Pending Zone Orders",
  "Market Fill at Zone",
  "Zone Proximity (ATR)",
  "Zone Watch Expiry (hours)",
  "Cooldown (minutes)",
  "Confirmation Method",
  "Per-Pair Gate Overrides",
  "Min R:R",
  "Min Tier 1",
  "Min Confluence %",
  "Max Per Symbol",
  "Allow Stacking",
  "Max Daily Loss ($)",
  "Max Consec Losses",
] as const;

const exitLabels = [
  "Stop Loss",
  "SL Method",
  "ATR Multiple",
  "Fixed SL (pips)",
  "SL Buffer (pips)",
  "Max SL (pips)",
  "Min SL (pips)",
  "Take Profit",
  "TP Method",
  "R:R Target",
  "Fixed TP (pips)",
  "Primary TP Level",
  "TP ATR Multiple",
  "Enable Partial TP",
  "Close %",
  "At R-level",
  "Trade Management",
  "Auto Break-Even",
  "Trigger (pips profit)",
  "Offset (pips)",
  "Enable Trailing",
  "Trailing Distance (pips)",
  "Activation",
  "Structure Invalidation",
  "Max Trade Duration",
  "Max Duration (hours)",
  "End-of-Session Close",
] as const;

const riskLabels = [
  "Position Sizing",
  "Starting Balance ($)",
  "Sizing Method",
  "Fixed Lot Size",
  "ATR Volatility Multiplier",
  "Risk per Trade (%)",
  "Standalone Size Multiplier",
  "Risk Limits",
  "Max Concurrent Trades",
  "Min R:R Ratio",
  "Max Portfolio Heat (%)",
  "Max Per Symbol",
  "Allow Same-Direction Stacking",
  "Drawdown & Circuit Breakers",
  "Max Daily Drawdown",
  "Max Total Drawdown",
  "Threshold Raise At",
  "Hard Block At",
  "Protection",
  "Max Daily Loss ($)",
  "Max Consecutive Losses",
  "Equity Circuit Breaker (%)",
] as const;

const scanAliases: AliasMap = {
  "Trading Style": ["scalper", "day trader", "swing", "mode"],
  "Scan Interval (minutes)": ["auto scan interval", "scanner frequency"],
  "News Event Filter": ["news filter", "nfp", "fomc", "cpi"],
  "News Buffer (minutes)": ["news pause", "news delay"],
  "Liquidity Pools": ["bsl", "ssl", "buy side liquidity", "sell side liquidity", "equal highs", "equal lows"],
  "Market Structure": ["bos", "choch", "market structure shift", "mss"],
  "Fair Value Gaps": ["fvg", "imbalance"],
  "AMD Phase": ["amd model", "accumulation manipulation distribution"],
  FOTSI: ["currency strength", "weakness"],
  "Direction Verdict Authority": ["direction verdict", "dv"],
  "Gameplan Hierarchy Audit": ["game plan hierarchy", "gameplan alignment"],
  "Bias Enforcement": ["game plan bias", "gameplan direction"],
  "Game Plan Enforcement": ["gameplan mode", "hard block", "soft scoring", "log only"],
  "Minimum Plan Confidence": ["gameplan confidence", "hard block threshold"],
  "Precision Filters": ["ict 2022", "validation gates"],
  "Kill Zones & Silver Bullet": ["kill zone", "silver bullet"],
};

const enterAliases: AliasMap = {
  "Confluence Threshold (%)": ["confluence threshold", "minimum score"],
  "Tier 1 Gate": ["tier 1 gate enabled", "core factor gate"],
  "Min Tier 1 Factors": ["min tier 1 core factors"],
  "Score Normalization": ["normalized scoring"],
  "Thesis Conviction": ["thesis validation", "thesis conviction tracker"],
  "Impulse Zone Gate Mode": ["zone gate", "require unified zone"],
  "Max Fib Retracement": ["fib depth", "ote", "88.6", "88 percent"],
  "Require Liquidity Sweep": ["sweep requirement", "entry trigger liquidity"],
  "Quality Threshold (0-100)": ["zone quality threshold"],
  "Min Displacement (ATR)": ["zone displacement"],
  "Pending Zone Orders": ["limit orders", "watchlist setup"],
  "Zone Watch Expiry (hours)": ["zone watch expiry", "setup expiry"],
  "Cooldown (minutes)": ["cooldown between trades"],
  "Confirmation Method": ["choch confirmation", "indicator confirmation"],
  "Per-Pair Gate Overrides": ["symbol overrides", "pair settings"],
  "Premium/Discount & Fib": ["premium discount weight", "fib weight"],
  "Fair Value Gap": ["fvg weight"],
  "Order Block": ["order block weight", "ob weight"],
};

const exitAliases: AliasMap = {
  "Fixed SL (pips)": ["fixed sl pips"],
  "ATR Multiple": ["atr multiple sl"],
  "Fixed TP (pips)": ["fixed tp pips"],
  "R:R Target": ["risk reward target", "rr ratio"],
  "Enable Partial TP": ["partial take profit"],
  "Auto Break-Even": ["break even", "breakeven", "be"],
  "Enable Trailing": ["trailing stop"],
  "Max Trade Duration": ["time based exit", "max hold"],
  "End-of-Session Close": ["friday close", "session close"],
};

const riskAliases: AliasMap = {
  "Position Sizing": ["position sizing method"],
  "Sizing Method": ["lot sizing", "fixed risk", "volatility adjusted"],
  "ATR Volatility Multiplier": ["atr multiplier", "volatility sizing"],
  "Max Portfolio Heat (%)": ["portfolio heat", "total exposure"],
  "Allow Same-Direction Stacking": ["same direction stacking", "pyramiding"],
  "Max Daily Drawdown": ["max daily drawdown percent"],
  "Max Total Drawdown": ["max total drawdown percent", "kill switch"],
  "Threshold Raise At": ["conflict threshold raise"],
  "Hard Block At": ["conflict hard block"],
  "Equity Circuit Breaker (%)": ["equity circuit breaker"],
};

export const BOT_CONFIG_SEARCH_CATALOG: BotConfigSearchEntry[] = [
  ...entries("scan", [...scanLabels], scanAliases),
  ...entries("enter", [...enterLabels], enterAliases),
  ...entries("exit", [...exitLabels], exitAliases),
  ...entries("risk", [...riskLabels], riskAliases),
];

function normalizeSearchText(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9%.$]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function searchBotConfigSettings(query: string): BotConfigSearchEntry[] {
  const terms = normalizeSearchText(query).split(" ").filter(Boolean);
  if (terms.length === 0) return [];

  return BOT_CONFIG_SEARCH_CATALOG.filter((entry) => {
    const haystack = normalizeSearchText(
      [entry.label, ...entry.keywords].join(" "),
    );
    return terms.every((term) => haystack.includes(term));
  });
}
